# Generated by Django 5.2.6 on 2025-10-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
