# Generated by Django 5.2.6 on 2025-11-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Indicates if the user is an admin of the team.'),
        ),
    ]
