# Generated by Django 5.2.6 on 2025-11-24 11:50

import TFapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFapp', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=TFapp.models.get_profile_pic_upload_path),
        ),
    ]
