# Generated by Django 5.2.6 on 2025-11-25 06:22

import TFapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFapp', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding',
            field=models.JSONField(blank=True, default=TFapp.models._zeros_300, help_text='300-d embedding vector (fastText)'),
        ),
        migrations.AddField(
            model_name='team',
            name='embedding',
            field=models.JSONField(blank=True, default=TFapp.models._zeros_300, help_text='300-d embedding vector (fastText)'),
        ),
        migrations.AddField(
            model_name='user',
            name='embedding',
            field=models.JSONField(blank=True, default=TFapp.models._zeros_300, help_text='300-d embedding vector (fastText)'),
        ),
    ]
