# Generated by Django 5.2.6 on 2025-11-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFapp', '0005_event_embedding_team_embedding_user_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='embedding_needs_update',
            field=models.BooleanField(default=False, help_text='If true, signal that embedding should be recalculated by async process'),
        ),
        migrations.AddField(
            model_name='team',
            name='embedding_needs_update',
            field=models.BooleanField(default=False, help_text='If true, signal that embedding should be recalculated by async process'),
        ),
        migrations.AddField(
            model_name='user',
            name='embedding_needs_update',
            field=models.BooleanField(default=False, help_text='If true, signal that embedding should be recalculated by async process'),
        ),
    ]
