# Generated by Django 5.2.6 on 2025-11-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFapp', '0006_event_embedding_needs_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='embedding_needs_update',
            field=models.BooleanField(default=True, help_text='If true, signal that embedding should be recalculated by async process'),
        ),
        migrations.AlterField(
            model_name='team',
            name='embedding_needs_update',
            field=models.BooleanField(default=True, help_text='If true, signal that embedding should be recalculated by async process'),
        ),
        migrations.AlterField(
            model_name='user',
            name='embedding_needs_update',
            field=models.BooleanField(default=True, help_text='If true, signal that embedding should be recalculated by async process'),
        ),
    ]
